name: Deploy Vite site to GitHub Pages

on:
  push:
    branches: [ main ]      # déclenche à chaque push sur main

concurrency:
  group: "pages"
  cancel-in-progress: true
  
permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Récupère le dépôt
      - name: Checkout
        uses: actions/checkout@v4

      # 2) Installe Node + met en cache le dossier npm
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      # 3) Installe les dépendances
      - name: Install deps
        run: npm ci

      # 4) Build en mode production (charge .env.production)
      - name: Build site
        env:
          ROLLUP_DISABLE_NATIVE: 1   # ← force Rollup à utiliser l’implémentation JS/WASM
        run: npm run build -- --mode production

      # 5) Déploie le dossier dist/ sur la branche gh‑pages
      - name: Deploy to gh‑pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist